import type { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import { SMART_ACCOUNT } from '../config/address';
import SMART_ACCOUNT_ABI from "../config/smartaccount.json"
import { ethers } from "ethers"
import { useEffect, useState } from 'react';

require("dotenv").config();

const Home: NextPage = () => {

  const [balance, setBalance] = useState("0")

  const getAccBalance = async () => {
    try {
      const provider = new ethers.JsonRpcProvider(process.env.NEXT_PUBLIC_RPC_URL)
      const smart_account_instance = new ethers.Contract(SMART_ACCOUNT, SMART_ACCOUNT_ABI, provider);

      const acc_balance = await smart_account_instance.getAccBalance();
      setBalance(ethers.formatEther(acc_balance))
    } catch (error) {
      console.log("ERROR: ", error);
    }
  }

  useEffect(() => {
    getAccBalance()
  }, [])

  return (
    <div className={""}>
      <Head>
        <title>Smart Account Wallet</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <div className="bg-[#2D4258] min-h-screen">

        <Navbar />
        <main className={"px-6 md:px-14 py-4 max-w-[1440px] mx-auto"}>


          <div className="grid grid-cols-2 gap-10">
            <div className="flex-1 w-full p-6 border border-[#1E293B] rounded-lg">


              <div className="">
                <h2 className='text-[#e8e8e8] text-xl mb-3 underline font-bold text-[24px]'>The Balance of this Smart Account is:</h2>

                <div className="text-white text-2xl font-bold">{balance} ETH</div>

              </div>
            </div>

          </div>
        </main>
      </div>
    </div>
  );
};

export default Home;
